### ISSUE TITLE
Connection error?

### ISSUE THREAD

**Issue by TristanWright** [Kitware/cumulus#90]
Haven't been able to run anythingt. Keep on getting this error: 

```python
[10:33:48.601] INFO: Downloading input for "myjob"
[10:33:48.609] ERROR: Job download/upload error: Traceback (most recent call last):
  File "girderclient.py", line 274, in <module>
    main()
  File "girderclient.py", line 270, in main
    config.token, config.url, config.job, config.dir).run()
  File "girderclient.py", line 212, in run
    r = requests.get(job_url, headers=self._headers)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
```

I've `vagrant destroy`'ed and `up/prevision`'ed a few times to no avail and I've made sure that the ip in the config.json is reachable from ulmus.

**Comment by TristanWright** [comment]
So I switched over to running on Beast and it's fine, the error above was happening on Ulmus though. Closing for now.
